
export const TERMS_CONTENT = `
    <h2>Terms and Conditions</h2>
    <p><strong>Last Updated: January 1, 2025</strong></p>
    <p>Welcome to Legally Legit AI ("we," "us," or "our"). These Terms and Conditions ("Terms") govern your use of our website, software, and services (collectively, the "Service"). By accessing or using the Service, you agree to be bound by these Terms.</p>

    <div style="border: 2px solid #d32f2f; padding: 1em; margin: 1em 0; border-radius: 8px; background-color: #ffebee;">
        <h3 style="color: #d32f2f; margin-top: 0;"><strong>IMPORTANT: No Legal Advice Provided</strong></h3>
        <p><strong>Legally Legit AI is a technology company, not a law firm. We do not provide legal advice, legal services, or legal representation.</strong></p>
        <p>The Service provides software for generating legal document templates and related informational analysis. This information is for educational and general informational purposes only and is not a substitute for, and should not be relied upon as, legal advice from a qualified solicitor who is licensed to practice in your jurisdiction and is familiar with your specific circumstances. <strong>Your use of the Service does not create a solicitor-client relationship between you and Legally Legit AI.</strong></p>
    </div>
    
    <h3>1. Your Responsibilities</h3>
    <p>You are solely responsible for:</p>
    <ul>
        <li>The accuracy, completeness, and legality of the information you provide to the Service.</li>
        <li>Determining the appropriateness of any document generated by the Service for your specific needs.</li>
        <li>Seeking independent legal advice from a qualified solicitor before using or relying on any document or information obtained from the Service.</li>
    </ul>

    <h3>2. Accounts and Subscriptions</h3>
    <p>To access certain features, you must create an account. You agree to provide accurate and complete information. Access to features may be offered on a free, one-time purchase, or recurring subscription basis. All payments are processed through our third-party payment processor (e.g., Stripe), and you agree to their terms of service.</p>
    
    <h3>3. Intellectual Property</h3>
    <p>The Service, its underlying technology, content, features, and functionality are the exclusive property of Legally Legit AI Pty Ltd and its licensors. We grant you a limited, non-exclusive, revocable license to use the Service to generate documents for your own business use. You may not resell or re-license the documents or otherwise exploit the Service for commercial purposes without our express written consent.</p>

    <h3>4. Australian Consumer Law</h3>
    <p>Our goods and services come with guarantees that cannot be excluded under the Australian Consumer Law. For major failures with the service, you are entitled:</p>
    <ul>
        <li>to cancel your service contract with us; and</li>
        <li>to a refund for the unused portion, or to compensation for its reduced value.</li>
    </ul>
    <p>You are also entitled to be compensated for any other reasonably foreseeable loss or damage. If the failure does not amount to a major failure, you are entitled to have the failure rectified in a reasonable time. If this is not done you are entitled to a refund for the goods and to cancel the contract for the service and obtain a refund of any unused portion.</p>

    <h3>5. Disclaimer of Warranties</h3>
    <p>Except for the guarantees provided under the Australian Consumer Law as described in Section 4, the Service is provided on an "as is" and "as available" basis. We do not warrant that the Service will be uninterrupted, error-free, or meet your specific requirements.</p>
    
    <h3>6. Limitation of Liability</h3>
    <p>To the fullest extent permitted by law (including the Australian Consumer Law), the total liability of Legally Legit AI Pty Ltd for any claim arising out of or relating to these Terms or the Service, regardless of the form of the action, is limited to the amount you paid to use the Service. Where liability cannot be excluded but can be limited, our liability is limited, at our option, to the re-supply of the services or the payment of the cost of having the services supplied again.</p>
    
    <h3>7. Termination</h3>
    <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will cease immediately.</p>

    <h3>8. Governing Law</h3>
    <p>These Terms shall be governed by and construed in accordance with the laws of the State of New South Wales, Australia, and the parties submit to the exclusive jurisdiction of the courts of that State.</p>
    
    <h3>9. Changes to Terms</h3>
    <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide at least 30 days' notice before any material changes take effect.</p>
`;

export const PRIVACY_POLICY_CONTENT = `
    <h2>Privacy Policy</h2>
    <p><strong>Last Updated: January 1, 2025</strong></p>
    <p>Legally Legit AI Pty Ltd ("we," "us," or "our") is committed to protecting your privacy. This Privacy Policy outlines how we handle your personal information in accordance with our obligations under the Australian <em>Privacy Act 1988 (Cth)</em> and the Australian Privacy Principles (APPs).</p>
    
    <h3>1. What Personal Information We Collect</h3>
    <p>We collect information necessary to provide our Service to you. This may include:</p>
    <ul>
        <li><strong>Identity and Contact Data:</strong> Your name and email address.</li>
        <li><strong>User-Provided Content:</strong> Any information you voluntarily enter into forms to generate documents. This can include names, addresses, ABNs, employment details, and other business or personal information related to you, your business, your employees, or your clients.</li>
        <li><strong>Financial Data:</strong> We do not store your credit card details. This information is provided directly to our third-party payment processors (e.g., Stripe).</li>
        <li><strong>Technical and Usage Data:</strong> Information about how you access and use our Service, including IP address, browser type, and interactions with our platform.</li>
    </ul>
    
    <h3>2. How We Use Your Personal Information</h3>
    <p>We use your personal information for the following purposes:</p>
    <ul>
        <li>To provide, operate, and maintain the Service.</li>
        <li>To process your requests and generate legal documents and AI analysis.</li>
        <li>To manage your account and process payments.</li>
        <li>To communicate with you, including sending service-related information and marketing materials (where you have consented).</li>
        <li>To improve our Service, troubleshoot issues, and for data analysis.</li>
    </ul>

    <h3>3. Disclosure of Your Personal Information</h3>
    <p>We may disclose your personal information to third parties in the following circumstances:</p>
    <ul>
        <li><strong>AI Service Providers:</strong> To generate documents and provide analysis, the **full content of the data you enter into our forms is sent to our third-party AI provider (e.g., Google's Gemini API).** This data is processed by them to provide the AI output. Their use of data is governed by their own privacy policies.</li>
        <li><strong>Service Providers:</strong> To third-party vendors who provide services such as payment processing, website hosting, and email delivery.</li>
        <li><strong>Legal Requirements:</strong> If required to do so by law or in response to valid requests by public authorities.</li>
    </ul>
    
    <h3>4. Cross-Border Disclosure of Personal Information</h3>
    <p>Our service providers, particularly our AI provider, may be located overseas. As such, your personal information may be transferred to and stored on servers in countries outside of Australia. We take reasonable steps to ensure that any overseas recipient of your personal information will handle it in a way that is consistent with the Australian Privacy Principles.</p>

    <h3>5. Data Storage and Security</h3>
    <p>We implement a variety of security measures to protect your information. Your data may be stored in your browser's local storage for a personalized experience and on secure cloud servers. While we take reasonable steps to protect your personal information, no method of transmission or electronic storage is 100% secure.</p>
    <p>We will comply with our obligations under the Notifiable Data Breaches (NDB) scheme in the event of an eligible data breach.</p>

    <h3>6. Your Rights and Access to Your Information</h3>
    <p>Under the Privacy Act, you have the right to:</p>
    <ul>
        <li>Request access to the personal information we hold about you.</li>
        <li>Request the correction of inaccurate personal information.</li>
        <li>Request that we delete your personal information, subject to certain legal obligations.</li>
    </ul>
    <p>You can manage some of your information directly through your dashboard. For other requests, please contact us using the details below.</p>

    <h3>7. Making a Complaint</h3>
    <p>If you believe we have breached the Australian Privacy Principles, please contact us first with your concerns. We will investigate your complaint and respond to you in writing within a reasonable period. If you are not satisfied with our response, you have the right to make a complaint to the Office of the Australian Information Commissioner (OAIC).</p>

    <h3>8. Contact Us</h3>
    <p>If you have any questions about this Privacy Policy or our privacy practices, please contact our Privacy Officer at:</p>
    <p>Email: <a href="mailto:admin@legallylegitai.com.au">admin@legallylegitai.com.au</a></p>
`;
